#!/usr/bin/env python3

import requests
import sys
from lxml import html


def dockerfile(packages, base):
    return

def debian_release_order(rel):
    return {'sid': 0,
            'squeeze': 11,
            'wheezy': 12,
            'jessie': 13,
            'stretch': 14,
            'buster': 15,
            'bullseye': 16,
    }.get(rel, -1)

def best_first(matched):
    rel_order = map(lambda rel: (debian_release_order(rel),rel), matched.keys())
    r = []
    for _,rel in sorted(rel_order, reverse=True):
        r.append((rel, matched[rel]))
    return r

def find_package(dep):
    base_url = 'https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords='
    rep = requests.get(base_url + dep)
    if not (rep.ok and rep.status_code == 200):
        raise Exception('!found "' + dep + '": ' + str(r.status_code))
    else:
        xml = html.fromstring(rep.text)
        search_results = xml.xpath('//div[@id="psearchres"]')
        matching = {}
        if len(search_results) == 0:
            raise Exception('!found "' + dep)
        else:
            for li in search_results[0].xpath('//a[@class="resultlink"]'):
                [_, rel, pkg] = li.get('href').split('/')
                pkgs = matching.get(rel, [])
                pkgs.append(pkg)
                matching[rel] = pkgs
        return best_first(matching)

# print(find_package('libboost1.55-all-dev'))
# print(find_package('libboost1.55'))
# print(find_package('libpurple'))

if len(sys.argv) < 2:
    print('Usage:  ', sys.argv[0], '<package name & maybe version>+')
    sys.exit(1)

print(list(map(find_package, sys.argv[1:])))
